Compiling milestone1 v0.1.0 (/home/thorium/Desktop/programming/2026/Rust/milestone1) error[E0308]: mismatched types    --> src/main.rs:191:47     | 191 | fn calculate_bmi(weight_kg:f64,height_m:f64)->f64{     |    -------------                              ^^^ expected , found     |    |     |    implicitly returns  as its body has no tail or  expression 192 | weight_kg/height_m*height_m;     |                            - help: remove this semicolon to return this value
For more information about this error, try Expected type did not match the received type.

Erroneous code examples:

```
fn plus_one(x: i32) -> i32 {
    x + 1
}

plus_one("Not a number");
//       ^^^^^^^^^^^^^^ expected `i32`, found `&str`

if "Not a bool" {
// ^^^^^^^^^^^^ expected `bool`, found `&str`
}

let x: f32 = "Not a float";
//     ---   ^^^^^^^^^^^^^ expected `f32`, found `&str`
//     |
//     expected due to this
```

This error occurs when an expression was used in a place where the compiler
expected an expression of a different type. It can occur in several cases, the
most common being when calling a function and passing an argument which has a
different type than the matching type in the function declaration..
error: could not compile  (bin milestone1) due to 1 previous error
solved by removing a semicolon